djangoShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path


from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='item_list'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('order-summary', OrderSummeryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('category/<str:slug>/', Post_By_Category.as_view(), name='category'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    ]

templates/_pegination.html
{% if page_obj.has_other_pages %}
<div class="container d-flex justify-content-center">
    <nav aria-label="Page navigation example">
     <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% for p in page_obj.paginator.page_range %}
            {% if page_obj.number == p %}
                <li class="page-item active"><a class="page-link">{{ p }}</a></li>
            {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                <li class="page-item"><a class="page-link" href="?{{ s }}page={{ p }}">{{ p }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?{{ s }}page={{ page_obj.next_page_number }}">NEXT</a></li>
        {% endif %}
     </ul>
    </nav>
</div>
{% endif %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"#}
{#          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>#}
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  rel="stylesheet"
/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
    <style>
        .card-body img {
            height: 300px;
        }
    </style>
</head>
<body>
{% include 'header.html' %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}

{% block body %}

{% endblock %}
{% include 'footer.html' %}

{% include 'scripts.html' %}
{% block extrascripts %}
{% endblock %}
</body>
</html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load cart_template_tags %}
{% block body %}
    <div class="container col-6">
        <form method="POST" class="needs-validation">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col-sm-12">
                    <label for="firstName" class="form-label">Имя</label>
                    {{ form.first_name }}
                </div>
                <div class="col-sm-12">
                    <label for="firstName" class="form-label">Фамилия</label>
                    {{ form.second_name }}
                </div>
                <div class="col-12">
                    <label for="username" class="form-label">Телефон</label>
                    {{ form.phone }}
                </div>
                <div class="col-12">
                    <label for="username" class="form-label">Адрес</label>
                    {{ form.address }}
                </div>
                <div class="col-12">
                    <label for="username" class="form-label">Тип заказа</label>
                    {% for value, name in form.fields.payment.choices %}
                        <div class="form-check">
                            <input id="{{ name }}" name="payment" value="{{ value }}" type="radio"
                                   class="form-check-input"
                                   required>
                            <label class="form-check-label" for="{{ name }}">{{ name }}</label>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-12">
                    <label for="username" class="form-label">Дата получения заказа</label>
                    {{ form.address }}
                </div>
            </div>
        <hr class="my-4">
            <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
        </form>
    </div>
{% endblock %}

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="container">
        <div class="row">

        </div>
    </div>
</footer>

templates/header.html
{% load cart_template_tags %}
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <p class="h5 my-0 me-md-auto fw-normal">Магазин Candyshop</p>
    <nav class="my-2 my-md-0 me-md-3">
        <a class="p-2 text-dark" href="/">Главная</a>
    </nav>
    {% if request.user.is_authenticated %}
        <a href="{% url 'core:order-summary' %}" class="btn btn-info" href="#">Корзина {{ request.user|cart_item_count }}</a>
        <a class="btn btn-outline-primary" href="{% url 'account_logout' %}">Выход</a>
    {% else %}
        <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Регистрация</a>
        <a class="btn btn-outline-primary" href="{% url 'account_login' %}">Вход</a>
    {% endif %}
</header>

templates/item_list.html
{% extends "base.html" %}
{% block title %} Главная {% endblock %}
{% load sidebar %}
{% block body %}


    <div class="container">
    <div class="row">
        <div class="col-lg-10">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Товары</h1>
            <p class="lead"></p>
        </div>

        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for e in items %}
                <div class="col">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-header">
                            <h4 class="my-0 fw-normal">{{ e.title }}</h4>
                        </div>
                        <div class="card-body">
                            <a href="{{ e.get_absolute_url }}"><img
                                    src="{{ e.image.url }}" class="card-img" alt="..."
                            ></a>
                            <h1 class="card-title pricing-card-title">{{ e.price }} <small
                                    class="text-muted">рублей</small></h1>

                            <a href="{{ e.get_absolute_url }}" class="w-100 btn btn-lg btn-outline-primary">Купить</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% include '_pegination.html' %}
        </div>
        <aside class="col-lg-2">
            {% get_cat %}
        </aside>
    </div>
    </div>
{% endblock %}

templates/order_summer.html
{% extends "base.html" %}
{% block body %}
    <main>
        <div class="container">
            <div class="table-responsive">
                <h2>Информация о заказе</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Название</th>
                        <th scope="col">Кол-вао</th>
                        <th scope="col">Цена</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.title }}</td>
                            <td>
                                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                            </td>

                            <td>{{ order_item.item.price }} рублей</td>
                            <td><a style="'color: red'" href="{% url 'core:remove-from-cart' order_item.item.slug %}"><i class="fas fa-trash-alt"></i></a></td>

                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">Ваша корзина пуста.</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <a class="btn btn-warning float-right ml-2" href="/">Продолжить покупки</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% if object.get_total %}
                        <tr>
                            <td colspan="2"><b>Общая цена:</b></td>
                            <td><b>{{ object.get_total }} рублей.</b></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <a class="btn btn-warning float-right ml-2" href="/">Продолжить покупки</a>
                                <a class="btn btn-primary float-right" href="/checkout/">Перейти к оформлению заказа</a>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </main>
{% endblock %}

templates/product.html
{% extends "base.html" %}
{% block title %} Главная {% endblock %}

{% block body %}
    <div class="container">
        <h1>{{ item.title }}</h1>
        <h3>Цена: {{ item.price }}рублей.</h3>
        <div class="row">
            <div class="col-md-2">
                <a href="{{ item.get_absolute_url }}"><img
                        src="{{ item.image.url }}" class="card-img-top" alt="..."></a>
            </div>
            <div class="col">
                <p>{{ item.characteristics|safe }}</p>
            </div>
            <div class="col-md-7">
                        <h3>Описание:</h3>
        <p>{{ item.description }}</p>
            </div>
        </div>

        <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary">Добавить в корзину</a>
        <a href="{{ item.get_remove_from_cart_url }}" class="btn btn-danger">Убрать из корзины</a>
    </div>

{% endblock %}

templates/scripts.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>